version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwordAPIKEY_123*
      - POSTGRES_DB=online_service_database
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/data/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api_rest_online:
    image: ${DOCKER_REGISTRY-}apirestonline
    build:
        context: .
        dockerfile: API_REST_ONLINE/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"


networks:
  postgres-network:
  redis-network:
